# db/products.yml

products:
  - title: "Ароматическая свеча с лавандой"
    description: >
      Помогает расслабиться перед сном и создаёт приятную атмосферу. 
      Горит до 40 часов.
  - title: "Ночная маска для сна"
    description: >
      Обеспечивает полную темноту и мягко прилегает к лицу. 
      Идеальна при сменном графике.
  - title: "Подушка с эффектом памяти"
    description: >
      Подстраивается под форму головы и шеи, 
      снижает нагрузку на позвоночник.
  - title: "Шумоподавляющие беруши"
    description: >
      Подходят для светочувствительных людей или тем, 
      кто живёт в шумной среде.
  - title: "Тёплый плед с хлопковым наполнителем"
    description: >
      Подходит для прохладных ночей, хорошо пропускает воздух 
      и не вызывает перегревания.
